#ifndef FROST_GLOBALS_H
#define FROST_GLOBALS_H

#define SERVER_NAME frost
#define SERVER_VERSION_MAJOR 0
#define SERVER_VERSION_MINOR 1
#define SERVER_VERSION_PATCH 0

#define STR1(arg) #arg
#define STR(arg) STR1(arg)

#define VERSION_STR STR(SERVER_NAME/SERVER_VERSION_MAJOR.SERVER_VERSION_MINOR.SERVER_VERSION_PATCH)

#endif //FROST_GLOBALS_H
